/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ysh_Sha */

#ifndef _Included_ysh_Sha
#define _Included_ysh_Sha
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ysh_Sha
 * Method:    sha256
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_ysh_Sha_sha256
  (JNIEnv *, jobject, jstring);

#ifdef __cplusplus
}
#endif
#endif
